package com.datu.patient;

import java.util.ArrayList;
import java.util.Date;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TileResponse implements java.io.Serializable {
  static final long serialVersionUID = 1L;
  private int tileResponseId;
  private int tileId;
  private int collectionId;
  private Boolean dismissFlag;
  private Date responseDateTime;
  private java.lang.String type;
  private java.util.List<TileResponseEngagement> tileResponseEngagements = new ArrayList<TileResponseEngagement>();

  public TileResponse() {
  }

  public int getTileResponseId() {
    return this.tileResponseId;
  }

  public void setTileResponseId(int tileResponseId) {
    this.tileResponseId = tileResponseId;
  }

  public int getTileId() {
    return this.tileId;
  }

  public void setTileId(int tileId) {
    this.tileId = tileId;
  }

  public int getCollectionId() {
    return this.collectionId;
  }

  public void setCollectionId(int collectionId) {
    this.collectionId = collectionId;
  }

  public Date getResponseDateTime() {
    return this.responseDateTime;
  }

  public void setResponseDateTime(Date responseDateTime) {
    this.responseDateTime = responseDateTime;
  }

  public java.lang.String getType() {
    return this.type;
  }

  public void setType(java.lang.String type) {
    this.type = type;
  }

  public java.util.List<TileResponseEngagement> getTileResponseEngagements() {
    return this.tileResponseEngagements;
  }

  public void setTileResponseEngagements(java.util.List<TileResponseEngagement> tileResponseEngagements) {
    this.tileResponseEngagements = tileResponseEngagements;
  }

  public java.lang.Boolean getDismissFlag() {
    return this.dismissFlag;
  }

  public void setDismissFlag(java.lang.Boolean dismissFlag) {
    this.dismissFlag = dismissFlag;
  }

  public TileResponse(int tileResponseId, int tileId, int collectionId, java.lang.Boolean dismissFlag,
      Date responseDateTime, java.lang.String type, java.util.List<TileResponseEngagement> tileResponseEngagements) {
    this.tileResponseId = tileResponseId;
    this.tileId = tileId;
    this.collectionId = collectionId;
    this.dismissFlag = dismissFlag;
    this.responseDateTime = responseDateTime;
    this.type = type;
    this.tileResponseEngagements = tileResponseEngagements;
  }

}