package com.datu.patient;

import java.util.Date;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Demographics implements java.io.Serializable {

  static final long serialVersionUID = 1L;
  private String firstName;
  private String middleName;
  private String lastName;
  private String genderCode;
  private Date birthDate;
  private int age;
  private String ethnicityCode;
  private String maritalStatus;

  public Demographics() {
  }

  public String getFirstName() {
    return this.firstName;
  }

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  public String getMiddleName() {
    return this.middleName;
  }

  public void setMiddleName(String middleName) {
    this.middleName = middleName;
  }

  public String getLastName() {
    return this.lastName;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  public String getGenderCode() {
    return this.genderCode;
  }

  public void setGenderCode(String genderCode) {
    this.genderCode = genderCode;
  }

  public java.util.Date getBirthDate() {
    return this.birthDate;
  }

  public void setBirthDate(java.util.Date birthDate) {
    this.birthDate = birthDate;
  }

  public int getAge() {
    return this.age;
  }

  public void setAge(int age) {
    this.age = age;
  }

  public String getEthnicityCode() {
    return this.ethnicityCode;
  }

  public void setEthnicityCode(String ethnicityCode) {
    this.ethnicityCode = ethnicityCode;
  }

  public String getMaritalStatus() {
    return this.maritalStatus;
  }

  public void setMaritalStatus(String maritalStatus) {
    this.maritalStatus = maritalStatus;
  }

  public Demographics(String firstName, String middleName, String lastName, String genderCode,
      java.util.Date birthDate, int age, String ethnicityCode, String maritalStatus) {
    this.firstName = firstName;
    this.middleName = middleName;
    this.lastName = lastName;
    this.genderCode = genderCode;
    this.birthDate = birthDate;
    this.age = age;
    this.ethnicityCode = ethnicityCode;
    this.maritalStatus = maritalStatus;
  }
}